---

- name: Install nginx
  apt:
    name: nginx
    state: present
  notify: Restart nginx
  tags: nginx

- name: Remove default nginx configuration
  file:
    name: '{{ item }}'
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
  tags: nginx

- name: Update the nginx config file
  ansible.builtin.template:
    src: ./templates/sites-enabled-default.conf.j2
    dest: /etc/nginx/sites-enabled/default
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx
  tags: nginx

- name: "Restart nginx {{ inventory_hostname }} "
  systemd_service:
    state: restarted
    enabled: true
    daemon_reload: true
    name: nginx
  register: servDetails
  until: servDetails.status.ActiveState == "active"
  delay: 10
  retries: 30

- name: Wait for nginx port to become open on the host
  wait_for:
    port: "{{ nginx_port }}"
    delay: 10
