---

- name: Stop mysql replica thread
  mysql_replication:
    mode: stopreplica
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: "{{ mysql_root_password }}"

# - name: "Change replication source to replica server {{ hostvars['mysql-master']['ansible_host'] }}"
#   mysql_replication:
#     mode: changereplication
#     primary_host: "{{ hostvars['mysql-master']['ansible_host'] }}"
#     primary_user: "{{ mysql_repl_user }}"
#     primary_password: "{{ mysql_root_password }}"
# #      master_log_file: mysql-bin.000009
#     primary_auto_position: 1
# #      master_log_pos: 1

- name: "Change replica source to get_source_public_key=1"
  ansible.builtin.command: 'mysql -p"{{ mysql_root_password }}" -NBe "{{ item }}"'
  with_items:
    - change replication source to source_host='{{ hostvars.mysql_master.ansible_host }}', source_user='{{ mysql_repl_user }}', source_password='{{ mysql_root_password }}', source_auto_position=1, get_source_public_key=1

- name: Start mysql replica thread
  mysql_replication:
    mode: startreplica
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: "{{ mysql_root_password }}"
