---

- name: "Install mysql {{ inventory_hostname }}"
  apt:
    name: mysql-server-8.0
    state: present
  notify: Restart mysql-slave
  tags: mysql-slave

- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest