---

- name: "Install mysql {{ inventory_hostname }}"
  apt:
    name: mysql-server-8.0
    state: present
  notify: Restart mysql-slave
  tags: mysql-slave

- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest

- name: Remove default mysql configuration
  file:
    name: '{{ item }}'
    state: absent
  loop:
    - /etc/mysql/mysql.conf.d/mysqld.cnf
  tags: mysql-slave

- name: Update mysql config file
  ansible.builtin.template:
    src: ./templates/mysqldslave.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: root
    group: root
  notify: Restart mysql-slave
  tags: mysql-slave

- name: Update mysql root user password
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
#    plugin: caching_sha2_password

- name: Stop mysql replica thread
  mysql_replication:
    mode: stopreplica
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: "{{ mysql_root_password }}"

# - name: "Change replication source to replica server {{ hostvars['mysql-master']['ansible_host'] }}"
#   mysql_replication:
#     mode: changereplication
#     primary_host: "{{ hostvars['mysql-master']['ansible_host'] }}"
#     primary_user: "{{ mysql_repl_user }}"
#     primary_password: "{{ mysql_root_password }}"
# #      master_log_file: mysql-bin.000009
#     primary_auto_position: 1
# #      master_log_pos: 1

- name: "Change replica source to get_source_public_key=1"
  ansible.builtin.command: mysql -NBe "change replication source to source_host='{{ hostvars['mysql-master']['ansible_host'] }}', source_user='{{ mysql_repl_user }}', source_password='{{ mysql_root_password }}', source_auto_position=1, get_source_public_key=1;"

  #mysql -NBe "SELECT Host FROM mysql.user WHERE User = ''"

- name: Start mysql replica thread
  mysql_replication:
    mode: startreplica
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: "{{ mysql_root_password }}"
