---

# - name: MAIN
#   hosts: nginx
#   become: true
#   roles:
#     - common
#     - nginx

# - name: Mysql-master
#   hosts: mysql_master
#   become: true
#   roles:
#     - common
#   #  - apache
#     - mysql-master

- name: Mysql-slave
  hosts: mysql_slave
  become: true
  roles:
    - common
  #  - apache
    - mysql-slave