---

- name: "Create {{ mysql_repl_user }} user"
  mysql_user: 
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}" 
    name: "{{ mysql_repl_user }}"
    password: "{{ mysql_root_password }}" 
    host: "%" 
    state: present
    plugin: caching_sha2_password
    priv: "*.*:REPLICATION SLAVE"

- name: "Create {{ mysqld_exporter_user }} user"
  mysql_user: 
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}" 
    name: "{{ mysqld_exporter_user }}"
    password: "{{ mysqld_exporter_password }}" 
    host: 'localhost'
    state: present
    #plugin: caching_sha2_password
    priv: "*.*:REPLICATION CLIENT,PROCESS,SELECT"
