---

- name: "Install grafana {{ inventory_hostname }}"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - adduser
    - libfontconfig1
    - musl

- name: Copy grafana_11.22.2
  copy:
    src: /home/liliya/grafana_11.2.2_amd64-224190-c9d6aa.deb
    dest: /tmp/grafana_11.2.2_amd64-224190-c9d6aa.deb

- name: Install a grafana.deb package
  apt:
    deb: /tmp/grafana_11.2.2_amd64-224190-c9d6aa.deb

- name: Restart service grafana, in all cases, also issue daemon-reload to pick up config changes
  systemd_service:
    state: restarted
    enabled: true
    daemon_reload: true
    name: grafana-server
  
- name: Wait for grafana, prometheus port to become open on the host
  wait_for:
    port: "{{ item }}"
    delay: 10
  loop:
   - 3000
   - 9090

- name: create prometheus datasource
  grafana_datasource:
    name: prometheus
    ds_type: prometheus
    ds_url: http://localhost:9090
    url_username: "admin"
    url_password: "admin"
    url: http://localhost:3000
    access: proxy
    uid: "de3ebdbwzvocgf"
    org_id: 1
    additional_json_data:
      httpMethod: "POST"
    tls_skip_verify: true
    
    # additional_json_data:
    #   httpHeaderName1: "Authorization"
    # additional_secure_json_data:
    #   httpHeaderValue1: "Bearer ihavenogroot"

- name: Copy dashboard
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - "mysql_overview_dashboard.json"
    - "nginx_dashboard.json"
    - "node_exporter_full_dashboard.json"

# - name: Export dashboard
#   grafana_dashboard:
#     grafana_url: http://localhost:3000
#     grafana_user: "admin"
#     grafana_password: "admin" #"{{ grafana_password }}"
#     org_id: 1
#     state: export
#     uid: "de3ebdbwzvocgf"
#     path: "/tmp/{{ item }}"
#   loop:
#     - "node_dashboard.json"
#     - "mysql_overview_dashboard.json"
#     - "nginx_dashboard.json"

- name: Import dashboard
  grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: "admin" #"{{ grafana_password }}"
    org_id: 1
    state: present
 #   folder: Dashboards
 #   uid: "MQWgroiiz"
    path: "/tmp/{{ item }}"
  loop:
    - "mysql_overview_dashboard.json"
    - "nginx_dashboard.json"
    - "node_exporter_full_dashboard.json"






# - name: Remove default prometheus configuration
#   file:
#     name: '{{ item }}'
#     state: absent
#   loop:
#     - /etc/prometheus/prometheus.yml

# - name: Update prometheus config file
#   ansible.builtin.template:
#     src: ./templates/prometheus.yml.j2
#     dest: /etc/prometheus/prometheus.yml
#     mode: 0644
#     owner: root
#     group: root

