---

- name: Create prometheus-nginx-exporter.service
  ansible.builtin.template:
    src: ./templates/prometheus-nginx-exporter.service.j2
    dest: /lib/systemd/system/prometheus-nginx-exporter.service
    mode: 0644
    owner: root
    group: root
