---

- name: Wait for nginx port to become open on the host
  wait_for:
    port: "{{ nginx_port }}"
    delay: 5

- name: Create prometheus-nginx-exporter.service
  ansible.builtin.template:
    src: ./templates/prometheus-nginx-exporter.service.j2
    dest: /lib/systemd/system/prometheus-nginx-exporter.service
    mode: 0644
    owner: root
    group: root
