---

- name: "Install prometheus-exporter {{ inventory_hostname }} {{ prometheus_exporter_types }}"
  apt:
    name: "prometheus-{{ item }}-exporter"
    state: present
  loop: "{{ prometheus_exporter_types }}"
