---

- name: Remove default mysql configuration
  file:
    name: '{{ item }}'
    state: absent
  loop:
    - /etc/mysql/mysql.conf.d/mysqld.cnf
  tags: mysql

- name: Update mysql config file
  ansible.builtin.template:
    src: ./templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: root
    group: root
  notify: Restart mysql
  when: mysql_type == master
  tags: mysql

- name: Update mysql config file
  ansible.builtin.template:
    src: ./templates/mysqldslave.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: root
    group: root
  notify: Restart mysql
  when: mysql_type == slave
  tags: mysql

