---

- name: Update mysql root user password
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
#    plugin: caching_sha2_password