---

- name: Update mysql root user password
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: ''
    name: "{{ mysql_root_user }}"
    host_all: yes
    password: "{{ mysql_root_password }}"
#    plugin: caching_sha2_password